spring:
  profiles:
    active: dev
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: rootR
    password: 123456
    url: jdbc:mysql://localhost:3306/Vue?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource